services:
  seed:
    build:
      context: .workspace/${SQL_SERVER}/${MARIADB_VERSION}
      dockerfile: Dockerfile
    tty: true
    env_file:
      - ./.env
    environment:
      MARIADB_ROOT_PASSWORD: root
    working_dir: /var/www/html
    volumes:
      - ./code:/var/www/html
      - /var/www/html/vendor
      - ~/.composer:/var/www/.composer:cached
      - seed_mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    extra_hosts:
      - 'seed:127.0.0.1'
      - 'host.docker.internal:host-gateway'

volumes:
  seed_mysql: