services:
  seed:
    build:
      context: .workspace/php-cli/${PHP_VERSION}
      dockerfile: Dockerfile
    tty: true
    env_file:
      - ./.env
    working_dir: /var/www/html
#    networks:
#      - seedNetwork
    volumes:
      - ./code:/var/www/html
      - /var/www/html/vendor
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - seed_mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    extra_hosts:
      - 'seed:127.0.0.1'
      - 'host.docker.internal:host-gateway'

volumes:
  seed_mysql: