#!/usr/bin/env php
<?php

declare(strict_types=1);

set_time_limit(0);

ini_set('memory_limit', '-1');

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

const SEED_ROOT = __DIR__;

require __DIR__ . '/vendor/autoload.php';

use Seed\Commands\Ddl;
use Seed\Commands\Export;
use Seed\Commands\Import;
use Seed\Commands\Profiles;
use Seed\Commands\Sed;
use Symfony\Component\Console\Application;


$application = new Application();

$application->addCommands(
    [
        new Profiles(),
        new Sed(),
        new Import(),
        new Ddl(),
        new Export(),
    ]
);

$application->run();