#!/usr/bin/env php
<?php

declare(strict_types=1);

set_time_limit(0);

ini_set('memory_limit', '-1');
ini_set('max_execution_time', '0');
ini_set('post_max_size', '0');

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
ini_set('error_reporting', E_ALL);


const SEED_ROOT = __DIR__;

require __DIR__ . '/vendor/autoload.php';

use Seed\Commands\Profiles;
use Seed\Commands\Seed;
use Symfony\Component\Finder\Finder;

$finder = new Finder();
$finder->in('./');


use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands(
    [
        new Profiles(),
        new Seed(),
    ]
);

$application->run();